apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-restapi
  labels:
    app: go-restapi-app
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: go-restapi-app
        tier: frontend
    spec:
      containers:
        - name: go-restapi-app
          image: 'gcr.io/rest-api-go-203406/go_restapo'
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8000