apiVersion: v1
kind: Service
metadata:
  name: go-restapi
  labels:
    app: go-restapi-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: go-restapi-app
    tier: frontend